### PR TITLE
Remove space around LI to remove unwanted border

### PR DESCRIPTION
**Pull request by campino2k**
This fixes spacing in FF in project header.

### CODE REVIEW

**Comment by fguillot** [comment]
I tested your PR but I don't see any difference. What border are you talking about?

**Comment by campino2k** [comment]
image

This one. Seeing it in Opera, Firefox and Chrome.

**Comment by fguillot** [comment]
I don't see this border with latest version of Chrome and Firefox, but why not.

**Comment by campino2k** [comment]
Thank you. Using latest Firefox on Linux, this is visible and gets fixed by removing those spaces. :man_shrugging:

**Pull request merged**
